# Generated by Django 6.0.3 on 2026-03-18 13:16

import web.models.character
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_character'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='background',
        ),
        migrations.AddField(
            model_name='character',
            name='background_image',
            field=models.ImageField(default='', upload_to=web.models.character.background_image_upload_to),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='character',
            name='photo',
            field=models.ImageField(upload_to=web.models.character.photo_upload_to),
        ),
    ]
